### ISSUE TITLE
Request for Signup Page

### ISSUE THREAD

**Issue by anshulporwal26** [monizb/FireShort#101]
**Is your feature request related to a problem? Please describe.**
I see there's a login screen, but no signup page. How does a user sign ups to this platform?

**Describe the solution you'd like**
I'd like to create a signup page and persist user data on localStorage on both login and signup.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by monizb** [comment]
@anshulporwal26 thanks for the issue, although this has already been worked upon and ready to be merged :)

**Comment by monizb** [comment]
Fixed with #79
