### ISSUE TITLE
Development Version of firebase imported in src/Component/Home.js - autoclosed

### ISSUE THREAD

**Issue by abhinavkrin** [monizb/FireShort#108]
The firebase was imported in the wrong formation Home.js
![Annotation 2020-10-04 012235](https://user-images.githubusercontent.com/15830206/95000622-2a92a980-05e0-11eb-97f1-aa27be8f3740.png)

**Comment by monizb** [comment]
@abhinavkrin thanks for the issue, yes this was the issue from long but I never got around fixing so maybe this should be the right time to do that, can you please confirm in which files we are importing Firebase Modules

**Comment by monizb** [comment]
@abhinavkrin sorry for the autoclose

**Comment by abhinavkrin** [comment]
No problem. I have fixed this issue in PR #109
