### ISSUE TITLE
Cannot create account on Sign up page

### ISSUE THREAD

**Issue by pyplacca** [monizb/FireShort#111]
**Describe the bug**
I keep getting a sign up error when I attempt to create an account on the sign up page

**To Reproduce**
1. Go to 'sign up page' or click on sign up on login page.
2. Fill form. 
3. Click on sign up button.
4. See error (*An unknown error occurred while signing up.*) above the sign up button.
5. Error **auth.js:204 POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/signupNewUser?key=[API_KEY] 400** also appears in the console

**Expected behavior**

**Desktop**
 - OS: Windows
 - Browser: Chrome
 - Version 85.0.4183.121

**Comment by monizb** [comment]
@pyplacca thanks for the issue, although I am unable to reproduce this and looks like there is a problem in the way you have set up Firebase, please check the following:

1) You have created a `.env` file in the root folder with all the variables exactly mentioned in the README file
2) You have not made errors in copying the values from Firebase Console onto the .env file
3) You have enabled email and password signup on Firebase Console

**Comment by pyplacca** [comment]
Awesome! 
Apparently, I was missing step 3.
Thanks @monizb
