### ISSUE TITLE
Add Protect Link With Password While Creating The Link

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#112]
Right now links can be protected only after creating them by clicking on the lock icon. It would be better If it could be added while creating the link itself under the activity tracking switch and if left blank it should not protect the link.

**Comment by pyplacca** [comment]
I'd like to take a shot at it

**Comment by monizb** [comment]
@pyplacca please go ahead

**Comment by pyplacca** [comment]
Great! I'll try to make a PR as soon as I can
