### ISSUE TITLE
Show a message when no links are available

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#117]
**Is your feature request related to a problem? Please describe.**
Right now when there are no links present on first login of the user, the page remains blank without any message being shown

**Describe the solution you'd like**
Add a message saying no links present with a good matching illustration indicating it and a swirly arrow pointing towards the add button on the bottom right

**Additional context**
<br>
<img width="1440" alt="Screenshot 2020-10-05 at 9 34 17 AM" src="https://user-images.githubusercontent.com/46259712/95039564-c01c5f00-06ee-11eb-8a06-ba59a18e6daf.png">

**Comment by prashantacharya** [comment]
HI, I'd like to contribute to this issue. Do I need some credentials (like firebase and stuff)?

**Comment by monizb** [comment]
> HI, I'd like to contribute to this issue. Do I need some credentials (like firebase and stuff)?

Hey, yes you will need a free Firebase account, just follow the README

**Comment by prashantacharya** [comment]
@monizb hey, just to be clear, we want to show this sign just the first time user signs in the app or we would like to display this everytime the user signs in to the platform?

**Comment by prashantacharya** [comment]
I'd like to propose an approach which in my opinion is better. I think showing a tooltip would be a lot better than using the arrows because I think it's difficult to point to the exact spot.

**Comment by monizb** [comment]
@prashantacharya the message and the images should appear always when the user has no links associated with his account like when:
1) The user has just signed up
2) The user has not created any links
3) The user deleted all his links

Basically everytime there are no links. Also the tooltip part wouldn't be ideal, what you could do instead is in the message also add "Press the `+` icon below to get started

**Comment by prashantacharya** [comment]
@monizb I'll have a look at it.

**Comment by TaarnStar** [comment]
Hi @monizb, is this issue still open (@prashantacharya can I help you perhaps)?

**Comment by prashantacharya** [comment]
@TaarnStar sure. I've been occupied with some work lately.

**Comment by TaarnStar** [comment]
@prashantacharya I have already made the showing of the message when no links are present (after loader is finished loading), I still have to put a bit of style in it. Maybe tomorrow will be finished and will send the PR

**Comment by TaarnStar** [comment]
@monizb I made two versions, can you tell me which would you prefer or if I must change something before i create a PR?


![image](https://user-images.githubusercontent.com/17704741/96374748-e6bda980-1174-11eb-9fea-a72f7035eee9.png)
![image](https://user-images.githubusercontent.com/17704741/96374751-eae9c700-1174-11eb-904d-f49b42dc9381.png)

**Comment by monizb** [comment]
hey @TaarnStar the message looks great, jus tplease change the background image to this: https://icons8.com/illustrations/illustration/pixeltrue-search 
Thanks!

**Comment by TaarnStar** [comment]
Hi @monizb, i see you merged the PR but the issues is still open. Is anything wrong with the PR and need to change anything?

**Comment by monizb** [comment]
@TaarnStar sorry I had not linked the PR to the issue so it didnt close automatically, thanks again!
