### ISSUE TITLE
Get a popup window dedicated to selecting a date and time for expiration

### ISSUE THREAD

**Issue by felizj17** [monizb/FireShort#132]
**Describe the solution you'd like**
Get a popup window like the one used for edit link but with dropdown calendar and time selection for the expiration date and time of the link.

**Comment by felizj17** [comment]
currently have a menu to open but this input is not a date input(calendar dropdown) or a time selector. I also thought of just putting the expire link setting within the edit link tab. Thoughts @monizb.

**Comment by monizb** [comment]
@felizj17 actually the calendar/time picker should be present both while creating the link and when you want to edit it, working with date-pickers across browsers is impossible until you are using an external independent package, the date picler should not allow past dates and times as well :)

**Comment by felizj17** [comment]
![fireshort](https://user-images.githubusercontent.com/37090868/96774410-f0812000-13b3-11eb-9fe7-f1f7a2453cc7.png)
this is how it looks now, none of the logic is in place yet
