### ISSUE TITLE
Add Protect Link With Password

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#14]
Add a new feature in each card/list where the user can check/uncheck the option to protect their link with a password, When this is enabled a password field should be presented to enter the password before redirecting to the destination link. It should track user information only if the password matches.

**Comment by harshvats2000** [comment]
Hey!
Looking forward to contribute on this one :)

**Comment by monizb** [comment]
Hey @harshvats2000 please go ahead :)

**Comment by harshvats2000** [comment]
I get an error "Unhandled Rejection (Error): Couldn't find your IP"
![Screenshot 2020-09-30 at 10 00 34 PM](https://user-images.githubusercontent.com/45518343/94713400-5ad01300-0368-11eb-9a5b-bd56cb2f9557.png)
Any ideas why am i getting this?

**Comment by monizb** [comment]
Hey @harshvats2000 have you done any code changes after you have cloned this repository also please make sure you are connected to the internet

**Comment by harshvats2000** [comment]
I didn't made any code changes yet and yes I am connected to good internet.

**Comment by monizb** [comment]
That's strange because I am unable to reproduce this issue, looks like its not able to detect your IP. Anyways this package had to be changed cause of its long wait  time and unpredictable behaviour, I have assigned this issue to someone already in #7 What you can do right now is maybe disable link tracking for the link you have created so that , the package doesn't run. Hope this will let you proceed.

**Comment by ibamibrhm** [comment]
@harshvats2000 that's because not all the connections have IPv6.

**Comment by monizb** [comment]
@ibamibrhm can't agree more, why didn't I ever think of that, thanks for the help! I'll just remove the IPV6 part as it doesn't add any value to the App as well

**Comment by monizb** [comment]
@harshvats2000 I have removed ipv6 tracking and now it should not throw an error to you, please first perform a git pull :)

**Comment by harshvats2000** [comment]
sure..Thanks!
