### ISSUE TITLE
Login page is narrowed on mobile

### ISSUE THREAD

**Issue by felizj17** [monizb/FireShort#145]
**Describe the bug**
when the site is accessed from an iphone, the login page is narrowed and parts are cut off
**To Reproduce**
1. when you start the local server visit on your phone using the ip address (e.g http://192.168.1.50:3000)
**Expected behavior**

**Screenshots**
![fireshort3 png](https://user-images.githubusercontent.com/37090868/97785182-cf6dbb80-1b79-11eb-8aef-62861e734429.jpg)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 11]
 - OS: [e.g. iOS 14.0.1]
 - Browser [e.g. chrome]

**Additional context**
mobile experience is important to most.

**Comment by monizb** [comment]
Hey @felizj17 sorry for the late reply, the login page will be revamped shortly to seamlessly fit across all devices :)
