### ISSUE TITLE
Revamping the Login And Registration Screen

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#165]
As mentioned in #145 the login screen is not at all Dynamic right now and does not add to a good UI. The following changes are required:

1) Revamping the entire signup/login form with the colour scheme to present a much better looking page
2) Make the login form responsive and auto-fit across all screen size to prevent hinderance.

Please do comment here before being assigned the issue :)

**Comment by Amit366** [comment]
Heyy I would like to work on this.

**Comment by monizb** [comment]
Sure please go ahaead @Amit366

**Comment by monizb** [comment]
You can also find more info for this Issue Here: https://github.com/monizb/FireShort/issues/99

**Comment by yashsehgal** [comment]
Hey Can I work on this issue?
