### ISSUE TITLE
Implement Code Splitting Using lazy()

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#168]
Right now the app downloads about 300kb of data just to redirect to the link which reduces the speed of the app and hinders  User's experience.So it would be a very good idea to implement Code Splitting using Lazy() to remove slow load times and make it nearly negligible.

Resources:
1) https://reactjs.org/docs/code-splitting.html
2) https://web.dev/code-splitting-suspense/

**Comment by ayushrastogi689** [comment]
I would like to work on this issue, I am a participant of SWoC.

**Comment by monizb** [comment]
Please go ahead @ayushrastogi689

**Comment by ayushrastogi689** [comment]
@monizb can you please tell me how to reach you. Your linkedin id?

**Comment by monizb** [comment]
Hey @ayushrastogi689 you can find me on the Discord Channel on the DWOC server's "Fireshort" Channel

**Comment by ashuvssut** [comment]
I will submit my PR for this issue the same day when assigned. please assign me this issue

**Comment by pranab2021** [comment]
I will work on this issue & I will submit my PR within a day .

**Comment by monizb** [comment]
@ayushrastogi689 are you still working on this or not?

**Comment by pranab2021** [comment]
sir this is a very easy task. taking more than 13days is an insane amount of time. Clearly, he is inactive. Please consider reviewing my PR.

**Comment by pranab2021** [comment]
I have done it within a day. Please consider my PR.

**Comment by monizb** [comment]
@ayushrastogi689 since you aren't responding, you are being unassigned
