### ISSUE TITLE
Search Funtionality Does Not Work With List View

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#169]
**Describe the bug**
Currently the search box for the links only works in the Card View where the cards are filtered out based on the input

**To Reproduce**
1. Go to Dashboard
2. Click on Search Box
3. Click On List View
4. List doesn't get filtered

**Expected behavior**
List should be filtered to give out matching results

**Comment by avinashupadhya99** [comment]
Hey can I work on this? Please assign this to me

**Comment by chait04** [comment]
Hey @monizb i would like to work on this issue

**Comment by monizb** [comment]
Hey @chait04 please go ahead :)

**Comment by chait04** [comment]
what about this 😕 
![Screenshot (65)](https://user-images.githubusercontent.com/59140343/107978918-9dc31800-6fe3-11eb-8bc7-0eed0c647d14.png)
