### ISSUE TITLE
Updating readme with various open-source programs like dwoc, hacktoberfest and some gifs

### ISSUE THREAD

**Issue by Sloth-Panda** [monizb/FireShort#175]
Let me know if this needs to be implemented

**Comment by monizb** [comment]
@Sloth-Panda I quite didn't get you here can you please elaborate

**Comment by Sloth-Panda** [comment]
Oh sorry for the last word its "gifs" and as your project has been a part of hacktoberfest and dwoc like opensource events it will be better to create an open-source section in readme and add these open-source programs images with a little description of them and for readme to look better few gifs (graphic interface format) may be used

**Comment by monizb** [comment]
Hey @Sloth-Panda since already all the participants come here from these event website directly we dont really need another place here describing these events, anyways thanks for the suggestion :)
