### ISSUE TITLE
Revamp Login Page

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#2]
Revamp the entire Login Page to look much better and make it more intuitive, The only requirement is you need to know basic React and CSS.

**Comment by RitikPandey1** [comment]
@monizb I would like to take this up

**Comment by monizb** [comment]
Please go ahead @RitikPandey1

**Comment by vikashgaya916** [comment]
started to work on this issue. Will post a mock-up once and then work on it.

**Comment by vikashgaya916** [comment]
<img width="1426" alt="Login-Page" src="https://user-images.githubusercontent.com/62158550/94966558-19cc3000-051b-11eb-92a5-d67449b8ce9a.png">

@monizb I came up with this simple design. Let me know your views.

**Comment by abhinavkrin** [comment]
![Screenshot_20201004_153416](https://user-images.githubusercontent.com/15830206/95012550-1b9b0e00-0657-11eb-9354-40667cb3209a.jpg)
The login page is not optimised for small screens

**Comment by monizb** [comment]
@abhinavkrin yup seen that, it's getting fixed in a PR already :)
