### ISSUE TITLE
Add Auto Link Expiry

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#21]
The users if wanted can set an end date and time for their links so that the link automatically expires and does not let the user redirect to the destination link. The only logic needed here is that if(current timestamp < end date timestamp) -> redirect else don't and show appropriate errors accordingly

**Comment by DevanshCodes** [comment]
Can I work on this? Can it be assigned?

**Comment by monizb** [comment]
Yes sure, please go ahead @DevanshCodes

**Comment by nitesh9001** [comment]
May i Know, What is exact time for expiry of link?

**Comment by monizb** [comment]
@nitesh9001 the expiry time is set by the admin and changes for each lin, ypu habe to present the admin a calendar and clock to choose the time, convert to timestamp and check if current timestamp is lesser than the expiry timestamp

**Comment by monizb** [comment]
@DevanshCodes  are you still on this?

**Comment by DevanshCodes** [comment]
Hey @monizb I'm not working on it. Sorry for the trouble, this issue can be picked up by anyone else.

**Comment by monizb** [comment]
@DevanshCodes cool. I think you should be more responsible about informing

**Comment by felizj17** [comment]
Hey @monizb started working on this but I'm unsure how to continue. I made a button to edit the expiration date but I I tried to start working on the function to control the button in Admin.js but just couldn't get it right and would love some help, thanks!
![fireshort](https://user-images.githubusercontent.com/37090868/96480855-c9d2b600-1208-11eb-8299-376ad7753117.png)

**Comment by monizb** [comment]
> Hey @monizb started working on this but I'm unsure how to continue. I made a button to edit the expiration date but I I tried to start working on the function to control the button in Admin.js but just couldn't get it right and would love some help, thanks!
> ![fireshort](https://user-images.githubusercontent.com/37090868/96480855-c9d2b600-1208-11eb-8299-376ad7753117.png)

Hey feliz, just create a separate issue, and please let me know in detail what you have tried and the code you have tried to implement and the errors if any and Ill help you out :)

**Comment by avinashupadhya99** [comment]
Hey, I want to work on this issue, can you please assign this to me?
Also, can the DWOC label be added to this if possible?

**Comment by monizb** [comment]
Hey @avinashupadhya99 sure please go ahead, adding the labels now
