### ISSUE TITLE
Show a Dialog after each link is created

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#22]
After each link is created, right now it only creates a corresponding card related to it. Instead of this, it should show a Dialog with the created link, a button to copy the link, different ways to share the URL and a button to generate a QR code and share it as a jpg

**Comment by paultech4u** [comment]
hey @monizb 
Looking forward to contribute on this one.

**Comment by monizb** [comment]
Hey @paultech4u please go ahead :)

**Comment by abhinavkrin** [comment]
hey,i would  like to contribute to this issue

**Comment by monizb** [comment]
Hey @abhinavkrin right now this issue has been assigned, do you want to look into other open issues?

**Comment by monizb** [comment]
@paultech4u are you still on this?

**Comment by paultech4u** [comment]
Yes,  I am almost done.

**Comment by monizb** [comment]
@paultech4u  no issues :)

**Comment by paultech4u** [comment]
No issues @monizb

**Comment by paultech4u** [comment]
@monizb the different way to share should I  include social media sharing also

**Comment by monizb** [comment]
@paultech4u yes please, also the QR code
