### ISSUE TITLE
Add a meaningful CONTRIBUTING.md file

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#23]
To comply fully with Github's community standards a well documented CONTRBUTING.md file is required to help first time contributors to contribute to this repository. You can use this guide [here](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors) to write a good one

**Comment by swaraj961** [comment]
Hi can i take this ?

**Comment by OverthinkersArea** [comment]
Pls assign this task to me

**Comment by monizb** [comment]
Sure @OverthinkersArea

**Comment by monizb** [comment]
#32 merged
