### ISSUE TITLE
Add a beautiful Home Page/Front Page

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#25]
Right now the App has no Front Page/ Home Page before the users login, it would be awesome to have a beautiful front page with illustrations, features and animations.Very good Feature Issue For contributors who love front end designing :)

**Comment by pilgrim-1610** [comment]
I'd like to work on  this

**Comment by monizb** [comment]
Please go ahead @pilgrim-1610

**Comment by GrumpyMonk26** [comment]
Has this been taken/completed??

**Comment by monizb** [comment]
@GrumpyMonk26 its up for grabs now, would you like to work on it?

**Comment by GrumpyMonk26** [comment]
@monizb yes i would like to work on it thanks :)

**Comment by niyasmhdth** [comment]
@GrumpyMonk26 can I work on the animation? I have been doing custom animation using after effects & Lottie animations, I thought of taking up this task, but I guess now its been already assigned. @monizb can multiple people work on the same task?

**Comment by monizb** [comment]
@GrumpyMonk26 please go ahead

**Comment by monizb** [comment]
> @GrumpyMonk26 can I work on the animation? I have been doing custom animation using after effects & Lottie animations, I thought of taking up this task, but I guess now its been already assigned. @monizb can multiple people work on the same task?

Hey @niyasmhdth would you be interested in making the login page even more beautiful and adding meaningful animations to it?

**Comment by niyasmhdth** [comment]
@monizb yes I would love to do that part.

**Comment by niyasmhdth** [comment]
@monizb can I start working on it? Revamp the login UI, with some animations

**Comment by monizb** [comment]
> @monizb can I start working on it? Revamp the login UI, with some animations

Yes please, also please raise an issue for the same, I will tell you some changes to be made and you can go ahead after that :)

**Comment by niyasmhdth** [comment]
@monizb  create a new feature issue, Revamp Login UI #99
