### ISSUE TITLE
Getting a cross origin error for geoip

### ISSUE THREAD

**Issue by ankitshekhawat** [monizb/FireShort#259]
**Describe the bug**
Redirects are stuck at a Fireshort screen. There is a CORS error for https://freegeoip.app/. followed by a  `FirebaseError: Function DocumentReference.set() called with invalid data. Unsupported field value: undefined (found in field country in document shorturls/...`

**To Reproduce**
1. Create a short url
2. Go to the short url
3. Open the browser console

**Expected behavior**
App redirects to the long URL as usual without a CORS error

**Screenshots**
![image](https://user-images.githubusercontent.com/5464540/126726283-2f6e00b3-fa6d-41e9-8ce9-fb42bf358a5c.png) 

**Desktop (please complete the following information):**
 - OS: MacOS 11.4
 - Browser: Chrome 91, Firefox 91
 - Version 91

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4
 - OS: Android 12 Beta
 - Browser Chrome / Firefox

**Comment by monizb** [comment]
Hey @ankitshekhawat ,
Thank you for raising an issue here, although I was not able to reproduce this issue. Can you please head over to https://fbls.ml which isFireshort's hosted version and let me know if you are able to reproduce this there. Thanks!

**Comment by ankitshekhawat** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/5464540/127083850-493abc93-0521-4974-9c3a-3f366abb3826.png">

Yeah, it looks my adblocker is blocking the https://freegeoip.app/ request. The moment I disable it for the URL it starts working.  I am using uBlock Origin.
