### ISSUE TITLE
Revamp the dashboard

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#3]
Revamp the design for the entire dashboard and make everything look pixel perfect and more clean. Requires basic knowledge of React and CSS.

**Comment by sushabhardy** [comment]
Hi @monizb I would like to take up this issue.

**Comment by monizb** [comment]
Hello @sushabhardy , please go ahead

**Comment by vikashgaya916** [comment]
@monizb is this issue available to be worked on? If yes, I would like to work on this.

**Comment by sushabhardy** [comment]
"Revamp" word should be clarified.

**Comment by monizb** [comment]
> "Revamp" word should be clarified.

Well, Revamp means you have to keep the original colors used in the App, but change it in a way that makes it look much better than what it is right now, make it more intuitive and beautiful
