### ISSUE TITLE
Add Signup Feature and Change Database Structure to hold data accordingly

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#4]
Feel free to work on the signup part where multiple users can register and have their own separate Admin panels rather than having one main Admin Panel.

Tasks:
1) Add Signup Feature
2) Change DB Structure to store data by UID for better security

To implement these you need to know Firestore Database and React.

**Comment by Ruchika30** [comment]
Hi @monizb . I would like to take this up. I know react. & would look into implementing firestore db

**Comment by monizb** [comment]
Hey @Ruchika30 , really glad to know that you would like to contribute, please do note thar Firebase DB is already a part of the application, and development of signup and then changing the data to be stored on user basis is required. I highly encourage you to run the app locally to get a better feel for it. Please feel free to ask any questions :)

**Comment by Ruchika30** [comment]
Hello @monizb . I would be able to take it up only on weekend due to certain unknown emergencies.  You can unassign the issue. I would check again on weekend if available. My apologoes

**Comment by monizb** [comment]
@Ruchika30 No problem, If anyone else is interested by then I'll assign it to them or you can do it whenever you are free :)

**Comment by abhinavkrin** [comment]
I would like to take this issue.

**Comment by monizb** [comment]
Please go ahead @abhinavkrin

**Comment by monizb** [comment]
@abhinavkrin just checking in, are you still working on this?

**Comment by abhinavkrin** [comment]
Yes i am working.
I have complete the signup functionality. Should i commit that part?

**Comment by abhinavkrin** [comment]
> @abhinavkrin just checking in, are you still working on this?

Hey, I have added the sign-up functionality with some other improvements. I have created the pull request. Could you go through it once?

**Comment by ArpitaGanatra** [comment]
Is this issue still open?
If yes, what are the problems faced?
