### ISSUE TITLE
Add confirmation dialog before deleting a link

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#41]
**Is your feature request related to a problem? Please describe.**
Right now the created links are deleted as soon as "Delete" is clicked, this is not ideal

**Describe the solution you'd like**
Add a confirmation dialog which first asks the user if they want to delete the link or not

**Comment by i-aryan** [comment]
Hey, I'd like to do it. Assign it please.

**Comment by haseeb1009** [comment]
I would like to add this confirmation dialog, can you please assign it to me?

**Comment by haseeb1009** [comment]
Oh I think I am 1 minute late to this. @i-aryan  just posted a comment when I was writing.

**Comment by monizb** [comment]
Hey @i-aryan please go ahead

**Comment by monizb** [comment]
@haseeb1009 there are a few more issues present, please have a look at them too :)

**Comment by haseeb1009** [comment]
@monizb  Right now almost all issues are already assigned. I will check when any new issue is opened.
