### ISSUE TITLE
Add a search bar to easily search for created links

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#42]
**Is your feature request related to a problem? Please describe.**
Right now if you have to search for your created links, you have to manually search them.

**Describe the solution you'd like**
Add a good looking search bar on top which should filter the cards as the user types into them giving them only the results they want, also please add a cross mark to clear the query and return all the cards back

**Comment by asi309** [comment]
I can work on this

**Comment by monizb** [comment]
Please go ahead @asi309

**Comment by akshayaugust21** [comment]
I want to work on this issue. Kindly assign it to me, I will complete both of the tasks.

**Comment by akshayaugust21** [comment]
I would complete the search functionality using the fuzzy search which would work even in the cases of spelling mistakes.
