### ISSUE TITLE
Develop APIs for all the tasks for easy management

### ISSUE THREAD

**Issue by JithinAntony4** [monizb/FireShort#47]
Developing API is important to get connect with other apps easily and securely.

Build minimal API for creating different links using an API key scheme (User)

**Comment by monizb** [comment]
Please go ahead @JithinAntony4 , please let me know what APIs you are developing, how are you managing the API keys and what are you using to develop them before you start :)

**Comment by JithinAntony4** [comment]
@monizb I'm creating API for CRUD links as well as viewing link stats. Each Admin have a unique API key (we setup multiple API keys for single account specify the scope of operation)

**Comment by monizb** [comment]
@JithinAntony4 thanks for clarifying. I suggest using Firebase Cloud Functions for an easy and seamless API development :)

**Comment by JithinAntony4** [comment]
@monizb I'm using Firebase Cloud Functions for this development

**Comment by monizb** [comment]
> @monizb I'm using Firebase Cloud Functions for this development

That's perfect 👍👍

**Comment by abhinavkrin** [comment]
> @monizb I'm using Firebase Cloud Functions for this development

 To deploy Firebase cloud functions billing needs to be enabled.

**Comment by JithinAntony4** [comment]
> > @monizb I'm using Firebase Cloud Functions for this development
> 
> To deploy Firebase cloud functions billing needs to be enabled.

@abhinavkrin  you can emulate Cloud Functions on locally
