### ISSUE TITLE
Fix List View To Contain All Features Of Card View

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#6]
Right now card view has a lot of features which list view doesn't, all you need to do is copy those features to list view and make the UI look better than it is right now.

**Comment by felizj17** [comment]
I would like to try to do this.

**Comment by monizb** [comment]
Please go ahead :)

**Comment by ampsteric** [comment]
I would like to work on this issue as well. please assign in case the issue is not resolved.

**Comment by monizb** [comment]
Hey @ampsteric this issue has been assigned currently, please look into #14 and let me know if you are interested.

**Comment by monizb** [comment]
@felizj17 are you stll on this?

**Comment by felizj17** [comment]
yes, does clicking on hits still do nothing on list view?

**Comment by monizb** [comment]
yes does nothing @felizj17

**Comment by felizj17** [comment]
alright ill see what i can do
