### ISSUE TITLE
Password Protection Option not present in Card Layout

### ISSUE THREAD

**Issue by rahul1995** [monizb/FireShort#61]
**Describe the bug**
In card layout, the whole feature of password-protection is not implemented.

**To Reproduce**
1. Go to 'Card Layout'.
2. See there is no lock/unlock icon for any link
3. Click 'Open' for any password-protected link.
4. Link opens up without prompting for password.

**Expected behavior**
Lock/Unlock icon should be shown and Password should be prompted for password-protected links in Card View.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rahul1995** [comment]
Could you please assign this to me?

**Comment by monizb** [comment]
Hey @rahul1995 the password protection was added just yesterday monly for the list view but It has to be implemented for Card view too, If you think you want to contribute to that part please go ahead

**Comment by monizb** [comment]
@rahul1995

**Comment by harshvats2000** [comment]
Hey @monizb Let me do this one too! Can you plz assign this to me? Thanks!

**Comment by monizb** [comment]
Hey @harshvats2000 sorry missed your comment, looks like this has been taken up already, do you mind looking at the other open PRs too? Thanks!

**Comment by rahul1995** [comment]
@monizb Can I increase width of the card as the lock icon doesn't have any room for it right now?

**Comment by monizb** [comment]
> @monizb Can I increase width of the card as the lock icon doesn't have any room for it right now?

Yes sure @rahul1995 whatever looks good should be fine, but please make sure the icon changes based on protected or not like in the list view

**Comment by rahul1995** [comment]
Fixed with PR https://github.com/monizb/FireShort/pull/81
