### ISSUE TITLE
Long-url is directly opened instead of getting redirected from our short url page from Card layout

### ISSUE THREAD

**Issue by rahul1995** [monizb/FireShort#62]
**Describe the bug**
If a link is opened through Card layout, the link is directly opened instead of getting redirected from short url.

**To Reproduce**
1. Go to Card View
2. Click on 'Open' for any link there
3. See that the long url is directly opened in new tab.

**Expected behavior**
Associated short url should be opened first which should redirect itself to long url as happening in List View.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rahul1995** [comment]
Can you please assign me this issue?

**Comment by monizb** [comment]
@rahul1995 When open is clicked we want the admin to directly go to the Long URL , we don't want to track unnecessary clicks or Ip address, hence that was done. Please reopen this issue if you have more questions :)

**Comment by rahul1995** [comment]
@monizb But in case of list view, it does all that stuff even for admin user.
