### ISSUE TITLE
Password being logged into the console for a password protected url.

### ISSUE THREAD

**Issue by vikashgaya916** [monizb/FireShort#68]
**Describe the bug**
When any user tries to open the short url, the password gets logged into the console.

**To Reproduce**
1. Open the short url in a browser.
2. Open Console of the browser.
3. If the link was password protected, the password get logged into the console.

**Expected behavior**
Should not be logged.

**Comment by monizb** [comment]
Hey @vikashgaya916 , thanks for raising the issue will look into this.
