### ISSUE TITLE
Reduce IP Tracking Time while redirecting to the destination link

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#7]
The app takes a minimum of 5 seconds to capture the User's IP Address When Redirecting to the destination link which is not at all ideal, It will be great if you can reduce this time drastically by using an alternative npm package or a free api. Right now it uses `public-api` package from NPM

**Comment by PranjalAgni** [comment]
I would like to work on this

**Comment by monizb** [comment]
Please go ahead @PranjalAgni

**Comment by PranjalAgni** [comment]
Hii there can you please add `eslint` and `prettier` in the project, as it helps to keep the coding style consistent. For now I have turned my formatter off as it overrides the styles

**Comment by monizb** [comment]
@PranjalAgni this repo uses Restyled to retyle the PRs and behind the hood it seems to be using Prettier already

**Comment by PranjalAgni** [comment]
Okay didn't new about that so does it means Restyled will automatically restyle my changes after opening the PR

**Comment by monizb** [comment]
@PranjalAgni yes you are right, when you create a PR it will mirror your PR and make another one with styled changes
