### ISSUE TITLE
Add more tracking options

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#8]
Right now the app tracks IPV4 address, IPV6 address and User-Agent. Add more tracking options like Country,date filters,Referrers etc. :)

**Comment by pepoflex** [comment]
Please assign me this project, I would love to work on it.

**Comment by monizb** [comment]
Hey @pepoflex  really glad to know that plese go ahead :)

**Comment by felizj17** [comment]
Hey @pepoflex you still working on this? I'd like to help or take over if you don't have the time.

**Comment by collectivecloudperu** [comment]
> Hola @pepoflex, ¿sigues trabajando en esto? Me gustaría ayudar o hacerme cargo si no tiene tiempo.

Right now I'm out of time brother, please continue.
