### ISSUE TITLE
Adding space as a short url breaks the app

### ISSUE THREAD

**Issue by TaarnStar** [monizb/FireShort#80]
**Describe the bug**
We are able to create the short links with spaces in it, but if we create that kind of short link and try to go to the link we shortened we get a console error

**To Reproduce**
1. Click on the button to create new short link
2. As the name of the link (in Custom URL) we put text with at least one space (for example _test space_
3. Click on button _shorten_
4. Click on the _eye_ icon (on the list type view) to go to the custom URL
5. The loader is constantly visible, the page doesn't redirect and in console we get an error

**Expected behavior**
When creating the Custom URL, I'm not able to put any spaces

**Screenshots**
![image](https://user-images.githubusercontent.com/17704741/94958960-a9101e00-04f0-11eb-98d3-de3ef0a7dcb9.png)
![image](https://user-images.githubusercontent.com/17704741/94958916-9c8bc580-04f0-11eb-8999-5af26f959188.png)
![image](https://user-images.githubusercontent.com/17704741/94959011-c04f0b80-04f0-11eb-9072-8657a3f3f98a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TaarnStar** [comment]
@monizb Issue opened, when you have the time you can assign me

**Comment by monizb** [comment]
@TaarnStar thanks for the issue! I'm assigning you to it :)

**Comment by monizb** [comment]
Fixed with #100
