### ISSUE TITLE
Clicking Hits does nothing in list view.

### ISSUE THREAD

**Issue by abhinavkrin** [monizb/FireShort#84]
**Describe the bug**
Clicking Hits does nothing in list view.

**Expected behavior**
Clicking Hits should open dialog that shows tracking of the curl.

**Comment by monizb** [comment]
Hey @abhinavkrin thanks for raising the issue, this has been raised already on #6 and is being worked on :)

**Comment by monizb** [comment]
@abhinavkrin I was wondering if you want to join in as a collaborator and help me review, merge and decline PRs since its becoming kind of hectic right now.
