### ISSUE TITLE
"Open" button behavior different across views

### ISSUE THREAD

**Issue by rahul1995** [monizb/FireShort#93]
**Describe the bug**
In List view, if admin clicks on "Open", link is opened through short link redirect, which also logs the tracking detail as well. But in Card view, it directly opens it without any tracking logs. 

**To Reproduce**
1. Go to 'List View'
2. Click on 'Open' for a link which is being tracked.
3. See the hits count incremented.
4. Do the same in 'Card View'
5. Hits count remain the same.

**Expected behavior**
Both views should have the same behaviour.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by monizb** [comment]
@rahul1995 thanks for pointing that out, ideally it should open the long URL just like the Card Layout, this should be an easy fix, let me know if you are interested.
