### ISSUE TITLE
Insecure Password Storage For Protected Links - autoclosed - autoclosed

### ISSUE THREAD

**Issue by monizb** [monizb/FireShort#98]
> @abhinavkrin that's not a problem, I'll keep the PR open so you can push all your commits and have one review and testing once you are ready. Thanks!

Hey @monizb, As I was working with the admin panel. I found out that the way the password is checked is insecure. The document has read access set to "public". And hence the password is exposed to the public. Also, once a password is set I could not find a way to remove the password.

Please look into the matter.
A solution would be to set a flag called "isProtected" set to true and storing the passwords in another collection.

_Originally posted by @abhinavkrin in https://github.com/monizb/FireShort/pull/79#issuecomment-702946944_

**Comment by Ayush-Mahajan** [comment]
Hi @monizb  I would like to work on this.

**Comment by monizb** [comment]
Sure please go ahead @Ayush-Mahajan ,please do follow the suggestion provided and make the security rules strong to avoid any vulenrability

**Comment by monizb** [comment]
@Ayush-Mahajan  sorry for the accidental close
