### ISSUE TITLE
Revamp Login UI

### ISSUE THREAD

**Issue by niyasmhdth** [monizb/FireShort#99]
Revamp Login UI to address changes and add animations

**Comment by monizb** [comment]
@niyasmhdth thanks for raising the issue, these are the changes required:

1) Right now the login page looks good, but It would be much better if it used the entire space on the page and if it looked like a proper split login screen 
![example](https://csform.com/wp-content/uploads/2018/04/Bank-login-panel.jpg)

2) Add a better background image, right now the left part of login screen has no background image, remove the existing animation form it and add a good background image like the reference image

3) Move the login form to the left and the left part to the right side, also increase the width of the form to 30% of the page and the other half should cover the rest

Design the page however you like keeping the reference pic in mind and remember to use the theme of black and white. All the best!

**Comment by niyasmhdth** [comment]
@monizb OK

**Comment by niyasmhdth** [comment]
@monizb please add the hacktoberfest label

**Comment by monizb** [comment]
@niyasmhdth which hactober label are you talking about?

**Comment by niyasmhdth** [comment]
@monizb is this task eligible for hacktober?

**Comment by monizb** [comment]
@niyasmhdth all PRs are eligible for Hacktoberfest on this repository, labeling is not required if your PR is merged :) It would be great if you could raise the PR by today

**Comment by niyasmhdth** [comment]
@monizb thanks for the update, will raise a PR today.

**Comment by niyasmhdth** [comment]
@monizb have initiated new PR for UI Revamp, Please do check
